spring:
  datasource:
    url: jdbc:mysql:///shop_1903
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.38.128:2181
  protocol:
    port: -1

